feat: Add init-sb command
AnimaApp/anima-dsa pull request #53
Opened 2023-06-08 13:12 UTC by BenAAndrew

2023-06-08 13:17 UTC, orarbel commented on packages/anima-cli/src/helpers/storybook.ts
> +    const res = await fetch(`${API_URL}/generate_storybook/`, {
for non-rest endpoint that are remote procedure calls we use the convention of `/rpc/` and without `/` suffix

```suggestion
    const res = await fetch(`${API_URL}/rpc/generate_storybook`, {
```

2023-06-08 13:18 UTC, orarbel commented on packages/anima-cli/src/helpers/storybook.ts
> +    return null;
best to add sentry report if fails

2023-06-09 13:05 UTC, BenAAndrew commented on packages/anima-cli/src/helpers/storybook.ts
> +    return null;
There are valid cases where the server will return a 400 because the passed code wasn't a component

2023-06-09 13:20 UTC, jorgemartins reviewed
Didn't know we're adding those feature, very cool. Added a comment regarding docs

2023-06-09 13:20 UTC, jorgemartins commented on README.md
> +
I've just deleted the contents of this file in the other PR. Maybe I merge to master and you update in the correct place(s)?

2023-06-14 09:25 UTC, jorgemartins commented on packages/anima-cli/src/commands/init-sb.ts
> +    log.yellow("Now run 'anima sync' to sync your project");
before running `anima sync` which btw should be `anima sync --storybook`, the user needs to build storybook first `npm run build-storybook`. (running the sync will prompt for the build so, they will learn by doing)

this makes me think, wdyt about prompting to "start storybook" (`npm run storybook`), so they can see the result of what the cli just did? something like `start storybook? (Y/n)`

2023-06-14 09:25 UTC, jorgemartins commented on packages/docs/guide/anima-cli/index.md
> +anima-storybook init-sb [option]
```suggestion
anima init-sb [option]
```

2023-06-14 09:26 UTC, jorgemartins commented on packages/anima-cli/README.md
> +anima-storybook init-sb [option]
```suggestion
anima init-sb [option]
```

2023-06-14 09:27 UTC, BenAAndrew commented on packages/anima-cli/src/commands/init-sb.ts
> +    log.yellow("Now run 'anima sync' to sync your project");
That's a good idea, I'll change the prompt to ask them to check the storybook

2023-06-14 10:41 UTC, andrico-anima commented on packages/anima-cli/src/commands/generate-storybook.ts
> +      componentsWithoutStorybook = files.filter(f => !f.includes(".test.") && !f.includes(".stories.") && !hasStorybook(files, f));
I know that there's a common testing library called `React Testing Library` that might use the `spec` or `test` suffix on a file. We might be skipping components because someone's written a unit test for it.

2023-06-14 10:42 UTC, andrico-anima commented on packages/anima-cli/src/commands/generate-storybook.ts
> +      componentsWithoutStorybook = files.filter(f => !f.includes(".test.") && !f.includes(".stories.") && !hasStorybook(files, f));
I know that Storybook suggest using `.stories.` in the file name, is there a reason why we're including `.test.` as well?

2023-06-14 10:44 UTC, andrico-anima commented on packages/anima-cli/src/commands/generate-storybook.ts
> +    let componentsWithoutStorybook: string[] = [];
Minor nitpick, but this isn't necessarily true, as a user can provide a component that they want to generate a story for, even if one already exists

A name like `componentsToGenerateStoryFor` is more accurate

2023-06-14 10:48 UTC, andrico-anima requested changes
No major concerns from me! A few minor comments, so just ping me when the comments are resolve (i'll leave the resolution up to you)

2023-06-14 11:41 UTC, BenAAndrew commented on packages/anima-cli/src/commands/generate-storybook.ts
> +        fs.rmSync(sampleStoriesPath, { recursive: true, force: true });
Sorry I should rename this variable. When you run `storybook init` it creates a folder of example stories so what this does is check if that folder exists before running the command, and if it doesn't it deletes it after. We could also leave the examples so I'll check what we want

2023-06-14 12:12 UTC, BenAAndrew commented on packages/anima-cli/src/commands/generate-storybook.ts
> +      componentsWithoutStorybook = files.filter(f => !f.includes(".test.") && !f.includes(".stories.") && !hasStorybook(files, f));
We're not excluding files that have a test, we're just skipping over files that contain ".test." in the path (because we can safely ignore test files), the component file (that does not have ".test.") will not be skipped

2023-06-14 13:15 UTC, andrico-anima commented on packages/anima-cli/src/commands/generate-storybook.ts
> +        fs.rmSync(sampleStoriesPath, { recursive: true, force: true });
Makes sense!

2023-06-14 13:16 UTC, andrico-anima commented on packages/anima-cli/src/commands/generate-storybook.ts
> +      componentsWithoutStorybook = files.filter(f => !f.includes(".test.") && !f.includes(".stories.") && !hasStorybook(files, f));
Sorry, that was my bad! I thought we were skipping components that already have a corresponding test/spec/stories file. 

In that case, what happens if a component already has a story?

2023-06-14 13:17 UTC, andrico-anima approved these changes
Thanks for making these changes

2023-06-14 13:42 UTC, BenAAndrew commented on packages/anima-cli/src/commands/generate-storybook.ts
> +      componentsWithoutStorybook = files.filter(f => !f.includes(".test.") && !f.includes(".stories.") && !hasStorybook(files, f));
Yes, we are currently skipping components that have a stories file (that's what the last check is: `!hasStorybook(files, f)`).

2023-06-26 15:08 UTC, andrico-anima approved these changes

2023-06-27 10:12 UTC, merged